export const ACCESS_TOKEN_REQUEST = "ACCESS_TOKEN_REQUEST";
export const ACCESS_TOKEN_VERIFICATION = "ACCESS_TOKEN_VERIFICATION";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const ACCESS_TOKEN_REFRESH = "ACCESS_TOKEN_REFRESH";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
